title: Dog Gallery
author: 이준범
email: 2jun888lee@gmail.com
subtitle: >-
  Main



social:
  facebook: user.jun888
  instagram: hi1i1i1h1i
  github: jjjuun888
  steam: "76561198904650672"

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  images:
    output: true
