title: Dog Gallery
author: 이준범
email: 2jun888lee@gmail.com
description: >-
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

social:
  twitter:
  facebook: user.jun888
  instagram: hi1i1i1h1i
  github: jjjuun888
  steam: 76561198904650672
  linkedin:

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  images:
    output: true
