title: Dog Gallery
author: 이준범
email: 2jun888lee@gmail.com
description: >-
  우리 집 강아지들(미르, 송이) 사진 올리는 간단한 웹페이지.
  내가 생각하기에 괜찮거나 잘 나온 사진만 업로드함.
  혹시나 업로드되었으면 하는 사진이 있다면 문의주셈.
  빠른 시일 내에 반영하겠음.

social:
  facebook: user.jun888
  instagram: hi1i1i1h1i
  github: jjjuun888
  steam: "76561198904650672"

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  images:
    output: true
