title: Dog Gallery
author: 이준범
email: 2jun888lee@gmail.com
description: >-
  이준범

subtitle: 우리 집 강아지들(미르, 송이) 사진 올리는 페이지.

social:
  facebook: user.jun888
  instagram: hi1i1i1h1i
  github: jjjuun888
  steam: "76561198904650672"

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  images:
    output: true
